name: flutter_news_app_bloc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.7
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.20.5
  get_it: ^8.0.3
  intl: ^0.20.1
  retrofit: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.14
  floor_generator: ^1.5.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.7

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
