name: flutter_news_app_bloc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  equatable: ^2.0.7
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.20.5
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  intl: ^0.20.1
  logger: ^2.5.0

dev_dependencies:
  floor_generator: ^1.5.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
